version: 2
updates:
  # Vue.js Frontend (npm)
  - package-ecosystem: "npm"
    directory: "/flairhq-vue"
    schedule:
      interval: "weekly"
      
  # Java Spring Boot Backend (Gradle)
  - package-ecosystem: "gradle"
    directory: "/flairhq-api"
    schedule:
      interval: "weekly"